// This file is generated by Velite

export { default as research } from './research.json'
export { default as projects } from './projects.json'
export { default as writing } from './writing.json'
export { default as cv } from './cv.json'