// This file is generated by Velite

import type __vc from '../velite.config.js'

type Collections = typeof __vc.collections

export type Research = Collections['research']['schema']['_output']
export declare const research: Research[]

export type Writing = Collections['writing']['schema']['_output']
export declare const writing: Writing[]

export type Cv = Collections['cv']['schema']['_output']
export declare const cv: Cv[]
